on:
  schedule:
    # NFL: Every 10 minutes on Saturday and Sunday from 7:30 AM to 8:00 PM LA time (Sept-Feb)
    - cron: '30,40,50 14 * 1-2,9-12 6'    # Saturday 7:30-7:50 AM LA
    - cron: '0,10,20,30,40,50 15-23 * 1-2,9-12 6'  # Saturday 8:00 AM-3:50 PM LA
    - cron: '0,10,20,30,40,50 0-3 * 1-2,9-12 6'    # Saturday 4:00-7:50 PM LA
    - cron: '0 4 * 1-2,9-12 6'                     # Saturday 8:00 PM LA
    
    - cron: '30,40,50 14 * 1-2,9-12 0'    # Sunday 7:30-7:50 AM LA
    - cron: '0,10,20,30,40,50 15-23 * 1-2,9-12 0'  # Sunday 8:00 AM-3:50 PM LA
    - cron: '0,10,20,30,40,50 0-3 * 1-2,9-12 0'    # Sunday 4:00-7:50 PM LA
    - cron: '0 4 * 1-2,9-12 0'                     # Sunday 8:00 PM LA
    
    # NFL: Hourly on all other days (Monday-Friday) during Sept-Feb
    - cron: '0 * * 1-2,9-12 1,2,3,4,5'    # Monday-Friday hourly
  workflow_dispatch:
  push:
    paths:
      - 'Week 1 model pred_updated.csv'
    branches:
      - main 
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    env: # API Keys must be before steps, and set as env variables
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr 
            any::tidyr
            any::readr
            any::janitor
            any::glue
            any::lubridate
            any::nflreadr
            any::httr
            any::jsonlite

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("NFL_Odds/R/nfl_odds.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
