on:
  schedule:
    # Every day at 10 AM UTC/6 AM ET (daylight savings time will change this)
    - cron: '0 10 * * *'
    # Every day at  8 PM UTC/4 PM ET (daylight savings time will change this)
    - cron: '0 20 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'cfb model output_new.csv'
    branches:
      - main 
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    env: # API Keys must be before steps, and set as env variables
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr 
            any::tidyr
            any::readr
            any::janitor
            any::glue
            any::lubridate
            any::nflreadr
            any::httr
            any::jsonlite
            any::stringr
            any::remotes
            sportsdataverse/cfbfastR

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("CFB_Odds/R/test_cfbfastr.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
